name: literature
channels:
  - conda-forge
  - defaults
dependencies:
  - argparse=1.4.0
  - build=0.8.0
  - click=8.1.3
  - cloudpickle=2.2.0
  - dask=2022.10.0
  - fsspec=2022.10.0
  - graphframes=0.6
  - locket=1.0.0
  - networkx=2.8.7
  - nose=1.3.7
  - numpy=1.23.4
  - packaging=21.3
  - pandas=1.5.1
  - partd=1.3.0
  - pep517=0.13.0
  - pip-tools=6.9.0
  - py4j=0.10.9.5
  - pyparsing=3.0.9
  - pyspark=3.3.0
  - python-dateutil=2.8.2
  - pytz=2022.5
  - pyyaml=6.0
  - six=1.16.0
  - tomli=2.0.1
  - toolz=0.12.0
  - wheel=0.37.1
  - build=0.8.0
  - click=8.1.3
  - cloudpickle=2.2.0
  - dask=2022.10.0
  - fsspec=2022.10.0
  - graphframes=0.6
  - locket=1.0.0
  - networkx=2.8.7
  - nose=1.3.7
  - numpy=1.23.4
  - packaging=21.3
  - pandas=1.5.1
  - partd=1.3.0
  - pep517=0.13.0
  - pip-tools=6.9.0
  - py4j=0.10.9.5
  - pyparsing=3.0.9
  - pyspark=3.3.0
  - python-dateutil=2.8.2
  - pytz=2022.5
  - pyyaml=6.0
  - six=1.16.0
  - tomli=2.0.1
  - toolz=0.12.0
  - wheel=0.37.1